### ISSUE TITLE
very many errors in "console"

### ISSUE THREAD

**Issue by MrThiemann** [RomRider/apexcharts-card#304] opened 2022-03-04 04:25 UTC
hey, I just noticed that the developer console is literally "overflowing" with the browser. .. that makes the whole thing unnecessarily slow.

is this known and does anyone know a remedy?

<img width="1436" alt="Bildschirmfoto 2022-03-04 um 05 20 31" src="https://user-images.githubusercontent.com/54147030/156699057-4be33bc3-1f3a-4062-831a-1db901aba8af.png">

**Comment by jazzmonger** [comment] 2022-03-26 02:17
I'm getting the same behavior.  Basically unusable.  Everything slows to a crawl.  I've been chasing this for days and finally realize it's Apex charts causing it.  It happened on one of the last few core updates. 

Bummer because it was a nice card.  Anyone know of another card that behaves?

**Comment by RomRider** [comment] 2022-04-09 12:49
Should be fixed with the upcoming update

**Comment by RomRider** [comment] 2022-04-09 12:50
Duplicate of #17

**Closed** 2022-04-09 12:50 UTC
Labels: bug
