### ISSUE TITLE
Blank Column

### ISSUE THREAD

**Issue by romquenin** [RomRider/apexcharts-card#121] opened 2021-03-04 22:00 UTC
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem (i think)

**Describe the bug**
Since the last update all my graphs with "column" are not displaying any column and if i don't add "datalabels" the card will be kind of blank

**Version of the card**
Version: 1.8.1

**To Reproduce**
This is the configuration I used:
```yaml
      - type: 'custom:apexcharts-card'   
        graph_span: 7d
        span:
          end: day      
        series:
          - color: 'rgb(235,10,104)'
            entity: sensor.tplink_1_today_energy_kwh
            type: column     
            group_by:
              func: max
              duration: 1d
            show:
              datalabels: true   
```

**Screenshots**
![Screenshot 2021-03-04 at 22 47 29](https://user-images.githubusercontent.com/34734431/110035181-9e75e100-7d3b-11eb-99ba-7903a091a3f9.png)

**Expected behavior**
Visible column.

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [88.0.4324.192 (Official Build) (x86_64)]

**Smartphone (please complete the following information):**
 - Device: [Android]
 - Browser [mobile app]
 - Version [last]

**Additional context**
I have tried several graph config with "columns" i've found on the forum and this repo with no success at all. I have tried to delete the card, reboot, install the card back, refresh cache, etc, etc.. 
Sorry for maybe a dumb config problem, but i'm completely stuck on this bug.
Thanks for your help.

**Comment by RomRider** [comment] 2021-03-05 13:43
I can't reproduce so far.

Multiple questions:
* Can you confirm the javascript console show the right version of apexcharts-card (ie. 1.8.1)
* Do you have any errors related to apexcharts-card in the javascript console?
* Is it working with `line` or `area`?
* Do you have a theme applied to your Home-Assistant instance
* What happens if you remove the `color` parameter?

**Comment by romquenin** [comment] 2021-03-05 15:22
Thank you for your help RomRider. It's really a weird issue.

- I can confirm i'm using the correct card version.
![Screenshot 2021-03-05 at 15 51 36](https://user-images.githubusercontent.com/34734431/110133114-315e5c00-7dcc-11eb-9f3d-915de59674a2.png)

- I do receive errors in the log, but only for this card i shared here (with a reduced config). My other card with the full config doesn't fire those errors:
```
apexcharts-card.js:1 Error: <svg> attribute height: Expected length, "NaN".
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
(anonymous) @ apexcharts-card.js:1
(anonymous) @ apexcharts-card.js:1
value @ apexcharts-card.js:1
_initialLoad @ apexcharts-card.js:852
async function (async)
_initialLoad @ apexcharts-card.js:852
connectedCallback @ apexcharts-card.js:808
build_card @ layout-card.js:1
(anonymous) @ layout-card.js:1
build_cards @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ app.2731154e.js:12773
_enqueueUpdate @ app.2731154e.js:12773
async function (async)
_enqueueUpdate @ app.2731154e.js:12773
requestUpdateInternal @ app.2731154e.js:12773
initialize @ app.2731154e.js:12773
initialize @ app.2731154e.js:12773
C @ app.2731154e.js:12773
T @ app.2731154e.js:12773
g @ layout-card.js:1
s @ chunk.bf78bb32ee89f3425ccf.js:3096
(anonymous) @ chunk.bf78bb32ee89f3425ccf.js:3096
d @ chunk.bf78bb32ee89f3425ccf.js:3096
c @ chunk.bf78bb32ee89f3425ccf.js:3096
a @ chunk.bf78bb32ee89f3425ccf.js:3096
value @ chunk.bcc24dc7f2504ad36740.js:2974
(anonymous) @ chunk.bcc24dc7f2504ad36740.js:2974
value @ chunk.bcc24dc7f2504ad36740.js:2974
value @ chunk.bcc24dc7f2504ad36740.js:2974
performUpdate @ app.2731154e.js:12773
_enqueueUpdate @ app.2731154e.js:12773
async function (async)
_enqueueUpdate @ app.2731154e.js:12773
requestUpdateInternal @ app.2731154e.js:12773
initialize @ app.2731154e.js:12773
C @ app.2731154e.js:12773
i @ chunk.bcc24dc7f2504ad36740.js:2974
value @ chunk.bcc24dc7f2504ad36740.js:3796
(anonymous) @ chunk.bcc24dc7f2504ad36740.js:2974
(anonymous) @ app.2731154e.js:12773
setTimeout (async)
(anonymous) @ app.2731154e.js:12773
handleEvent @ app.2731154e.js:12773
__boundHandleEvent @ app.2731154e.js:12773
s @ paper-buttons-row.js:1
(anonymous) @ paper-buttons-row.js:1
Promise.then (async)
(anonymous) @ paper-buttons-row.js:1
n @ paper-buttons-row.js:1
(anonymous) @ paper-buttons-row.js:1
(anonymous) @ paper-buttons-row.js:1
```
and:
```
apexcharts-card.js:1 Error: <svg> attribute height: Expected length, "NaN".
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
(anonymous) @ apexcharts-card.js:1
(anonymous) @ apexcharts-card.js:1
value @ apexcharts-card.js:1
(anonymous) @ apexcharts-card.js:1
setTimeout (async)
value @ apexcharts-card.js:1
value @ apexcharts-card.js:1
```
- I can confirm it's working for `line` but when i input `area` the graph look exactly the same.

![Screenshot 2021-03-05 at 16 05 12](https://user-images.githubusercontent.com/34734431/110133862-16d8b280-7dcd-11eb-9093-f868a53d5129.png)

- I did have a custom theme applied, i disabled it but nothing have changed.
- I had already removed the `color` parameter during my attempts to solve this issue by my own, with no success.

 Sorry to bother you with this...

**Comment by jostie123** [comment] 2021-03-05 23:36
Same problem here with the card. worked fine in column mode now only datalabels.

![image](https://user-images.githubusercontent.com/8819339/110185858-d3556700-7e13-11eb-8a34-cba8e0edade9.png)

my configuration

`  - type: 'custom:apexcharts-card'
    experimental:
      color_threshold: true
    graph_span: 20d
    all_series_config:
      opacity: 1
      type: column
    span:
      end: day
      offset: '-1d'
    header:
      show: false
    series:
      - entity: sensor.dagelijks_verbruik_lastperiod1
        group_by:
          func: max
          duration: 1d
        offset: +1d
        color_threshold:
          - value: 0
          - value: 12
            color: '#FF6600'
          - value: 18
            color: red
    apex_config:
      plotOptions:
        bar:
          horizontal: false
          dataLabels:
            position: bottom
            orientation: vertical
      dataLabels:
        enabled: true
        enabledOnSeries: false
        style:
          colors:
            - '#fff'
          fontSize: 12px
        background:
          enabled: false
      chart:
        height: 180px
      xaxis:
        labels:
          show: false
      yaxis:
        show: true
        opposite: true
        labels:
          align: left
        tooltip:
          enabled: true
      tooltip:
        enabled: true
        fixed:
          enabled: true
          position: topLeft
          offsetY: 10
          offsetX: 10
        x:
          show: false
          format: MMM d
        marker:
          show: false`

**Comment by jostie123** [comment] 2021-03-06 00:05
ok so just now i noticed that the graphs still worked on an other instance op HA but that one was not yet updated to core-2021.3.1 but i did already update the apexchart-card to 1.8.1

now after updating HA the graphs stopped working there to so looks like it is a problem coming from home assistant?

**Comment by romquenin** [comment] 2021-03-06 00:26
Interesting finding @jostie123, thanks for sharing. At least i know i'm not alone with this weird bug.

**Comment by RomRider** [comment] 2021-03-06 10:24
Seems like you are using card-mod, layout-card and stack-in-card. Would you mind just testing in a simple view with just the graph, then adding each addon until it breaks and report back?
I believe card-mod is the culprit but I'm not yet sure.

**Comment by romquenin** [comment] 2021-03-06 11:17
Thank you for your help RomRider, the `columns` now appears on a simple view when i disable `layout-card`:
![Screenshot 2021-03-06 at 12 13 51](https://user-images.githubusercontent.com/34734431/110204916-e3059780-7e75-11eb-9ab7-8d6dc709da03.png)

**Comment by RomRider** [comment] 2021-03-06 11:22
Great, thanks! I've managed to reproduce with layout-card, thanks. I'll have a look at it, not sure yet if it can be fixed on my side or if it's on layout-card's side.

**Comment by RomRider** [comment] 2021-03-06 11:36
So I don't know what happens with layout-card but it refreshes the card 5 times every time it needs a refresh... So I believe the issue is on layout-card's side...

**Comment by romquenin** [comment] 2021-03-06 11:42
Thanks for the feedback RomRider, i will try t get rid of it aswell.

**Comment by RomRider** [comment] 2021-03-06 11:43
Seems like there are already some reports here: https://github.com/thomasloven/lovelace-layout-card/issues/99

**Comment by romquenin** [comment] 2021-03-06 12:00
Problem solved when disabling `layout-card`:
![Screenshot 2021-03-06 at 12 52 42](https://user-images.githubusercontent.com/34734431/110205921-2282b280-7e7b-11eb-91fe-342630af6a2e.png)

Many thanks to you @RomRider! I enjoy your work and your commitment for the community. Cheers!

**Closed** 2021-03-06 12:16 UTC
Labels: bug

**Comment by RomRider** [comment] 2021-03-06 12:20
I've managed to fix it in the end, so you can re-integrate layout-card ;)

**Comment by romquenin** [comment] 2021-03-06 12:28
I think i can live without it, my ui display layout survived and the loadings seems a little faster. 
All Good for me, thanks for your support Rom!
