### ISSUE TITLE
Multiple stacks on same chart

### ISSUE THREAD

**Issue by Toukite** [RomRider/apexcharts-card#95] opened 2021-02-18 14:29 UTC
Hello, 

Would it be feasible to provide a way to display multiple stacks on the same chart ?

Something like this:
![image](https://user-images.githubusercontent.com/42780622/108371106-b149cb00-71fd-11eb-9e5d-80503d9a737e.png)

But where each column (the blue, the orange, the green), which represent different data, would be in fact a stack (the blue one divided in two or more, same for the orange, same for the green, etc...).

Don't hesitate to tell me if the need is unclear !

**Comment by RomRider** [comment] 2021-02-18 15:18
That is unfortunately not possible with ApexCharts. It seems to be the same request as #25

**Comment by RomRider** [comment] 2021-02-23 19:52
Duplicate of #25

**Closed by RomRider** 2021-02-23 19:52 UTC
Labels: feature-request
